/*
Activity Table 
*/

IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'DeletedUserID')
	ALTER Table Activity DROP COLUMN  DeletedUserID

IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'DeletedDate')
	ALTER Table Activity DROP COLUMN  DeletedDate

IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'IsDeleted' AND COLUMN_NAME = 'IsDeleted')
	ALTER Table Activity DROP COLUMN  IsDeleted

IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'ModifiedUserID')
	ALTER Table Activity DROP COLUMN  ModifiedUserID


IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'ModifiedDate')
	ALTER Table Activity DROP COLUMN  ModifiedDate


IF   EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'Code')
		ALTER Table Activity  ALTER COLUMN Code CHAR(5)


IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'CreatedUserID')
	ALTER Table Activity DROP COLUMN  CreatedUserID


IF  EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.[COLUMNS] WHERE TABLE_NAME = 'Activity' AND COLUMN_NAME = 'CreatedDate')
	ALTER Table Activity DROP COLUMN  CreatedDate
