select count(*)
FROM 
     [ORACLECRM]..[SCOTT].[BASE_BOOKHT] AS BB 
JOIN [ORACLECRM]..[SCOTT].[V_BOOKHT] AS VB ON  BB.[BOOKHT_ID] = VB.[BOOKHT_ID]
JOIN [ORACLECRM]..[SCOTT].[TELEPHONEINFORMATION] AS TI ON TI.[FI_CODE] = VB.[FI_CODE] 
JOIN [ORACLECRM]..[SCOTT].[ETESALI] AS ET ON ET.FI_CODE = TI.FI_CODE
JOIN [ORACLECRM]..[SCOTT].[CENTER] AS CEN ON TI.CENTER_CODE = CEN.CEN_CODE
JOIN [ORACLECRM]..[SCOTT].[CITY] AS CI ON CEN.[CI_CODE] = CI.[CI_CODE]
where BB.BOOKHT_TYPE = 21 and BB.BOOKHT_ID not in(SELECT bb.[BOOKHT_ID]
												  FROM [ORACLECRM]..[SCOTT].[PCM] as pc
												   join [ORACLECRM]..[SCOTT].[KAFU_PCM] as kp on kp.[PORT_ID] = pc.[PCM_ID]
												   join [ORACLECRM]..[SCOTT].[BASE_BOOKHT] as bb on bb.[BOOKHT_ID] =kp.[BOOKHT_ID])
GO
--230571
--213963