//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace CRM.Application.HelpDeskService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IHelpDeskService", Namespace="http://tempuri.org/")]
    public partial class HelpDeskService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReplyHelpDeskMDFInquiryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HelpDeskService() {
            this.Url = global::CRM.Application.Properties.Settings.Default.CRM_Application_HelpDeskService_HelpDeskService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReplyHelpDeskMDFInquiryCompletedEventHandler ReplyHelpDeskMDFInquiryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHelpDeskService/ReplyHelpDeskMDFInquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReplyHelpDeskMDFInquiry(long phoneNo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool phoneNoSpecified, long ticketNo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ticketNoSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string description, long requestId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool requestIdSpecified, out bool ReplyHelpDeskMDFInquiryResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReplyHelpDeskMDFInquiryResultSpecified) {
            object[] results = this.Invoke("ReplyHelpDeskMDFInquiry", new object[] {
                        phoneNo,
                        phoneNoSpecified,
                        ticketNo,
                        ticketNoSpecified,
                        description,
                        requestId,
                        requestIdSpecified});
            ReplyHelpDeskMDFInquiryResult = ((bool)(results[0]));
            ReplyHelpDeskMDFInquiryResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ReplyHelpDeskMDFInquiryAsync(long phoneNo, bool phoneNoSpecified, long ticketNo, bool ticketNoSpecified, string description, long requestId, bool requestIdSpecified) {
            this.ReplyHelpDeskMDFInquiryAsync(phoneNo, phoneNoSpecified, ticketNo, ticketNoSpecified, description, requestId, requestIdSpecified, null);
        }
        
        /// <remarks/>
        public void ReplyHelpDeskMDFInquiryAsync(long phoneNo, bool phoneNoSpecified, long ticketNo, bool ticketNoSpecified, string description, long requestId, bool requestIdSpecified, object userState) {
            if ((this.ReplyHelpDeskMDFInquiryOperationCompleted == null)) {
                this.ReplyHelpDeskMDFInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReplyHelpDeskMDFInquiryOperationCompleted);
            }
            this.InvokeAsync("ReplyHelpDeskMDFInquiry", new object[] {
                        phoneNo,
                        phoneNoSpecified,
                        ticketNo,
                        ticketNoSpecified,
                        description,
                        requestId,
                        requestIdSpecified}, this.ReplyHelpDeskMDFInquiryOperationCompleted, userState);
        }
        
        private void OnReplyHelpDeskMDFInquiryOperationCompleted(object arg) {
            if ((this.ReplyHelpDeskMDFInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReplyHelpDeskMDFInquiryCompleted(this, new ReplyHelpDeskMDFInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReplyHelpDeskMDFInquiryCompletedEventHandler(object sender, ReplyHelpDeskMDFInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReplyHelpDeskMDFInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReplyHelpDeskMDFInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ReplyHelpDeskMDFInquiryResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ReplyHelpDeskMDFInquiryResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591