//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BillingCRMServiceSoap", Namespace="http://tempuri.org/")]
public partial class BillingCRMService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetV_LastDebtOperationCompleted;
    
    private System.Threading.SendOrPostCallback DisconectTellNoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ConnectTellNoOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCounterOperationCompleted;
    
    /// <remarks/>
    public BillingCRMService() {
        this.Url = "http://192.168.240.52:8084/billingcrmservice.asmx";
    }
    
    /// <remarks/>
    public event GetV_LastDebtCompletedEventHandler GetV_LastDebtCompleted;
    
    /// <remarks/>
    public event DisconectTellNoCompletedEventHandler DisconectTellNoCompleted;
    
    /// <remarks/>
    public event ConnectTellNoCompletedEventHandler ConnectTellNoCompleted;
    
    /// <remarks/>
    public event GetCounterCompletedEventHandler GetCounterCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetV_LastDebt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public V_LastDebtInfo GetV_LastDebt(string FullPhoneNo, string UserName, string Password) {
        object[] results = this.Invoke("GetV_LastDebt", new object[] {
                    FullPhoneNo,
                    UserName,
                    Password});
        return ((V_LastDebtInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetV_LastDebt(string FullPhoneNo, string UserName, string Password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetV_LastDebt", new object[] {
                    FullPhoneNo,
                    UserName,
                    Password}, callback, asyncState);
    }
    
    /// <remarks/>
    public V_LastDebtInfo EndGetV_LastDebt(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((V_LastDebtInfo)(results[0]));
    }
    
    /// <remarks/>
    public void GetV_LastDebtAsync(string FullPhoneNo, string UserName, string Password) {
        this.GetV_LastDebtAsync(FullPhoneNo, UserName, Password, null);
    }
    
    /// <remarks/>
    public void GetV_LastDebtAsync(string FullPhoneNo, string UserName, string Password, object userState) {
        if ((this.GetV_LastDebtOperationCompleted == null)) {
            this.GetV_LastDebtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetV_LastDebtOperationCompleted);
        }
        this.InvokeAsync("GetV_LastDebt", new object[] {
                    FullPhoneNo,
                    UserName,
                    Password}, this.GetV_LastDebtOperationCompleted, userState);
    }
    
    private void OnGetV_LastDebtOperationCompleted(object arg) {
        if ((this.GetV_LastDebtCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetV_LastDebtCompleted(this, new GetV_LastDebtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisconectTellNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool DisconectTellNo(string FullPhoneNo, int CuaseID) {
        object[] results = this.Invoke("DisconectTellNo", new object[] {
                    FullPhoneNo,
                    CuaseID});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDisconectTellNo(string FullPhoneNo, int CuaseID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DisconectTellNo", new object[] {
                    FullPhoneNo,
                    CuaseID}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDisconectTellNo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DisconectTellNoAsync(string FullPhoneNo, int CuaseID) {
        this.DisconectTellNoAsync(FullPhoneNo, CuaseID, null);
    }
    
    /// <remarks/>
    public void DisconectTellNoAsync(string FullPhoneNo, int CuaseID, object userState) {
        if ((this.DisconectTellNoOperationCompleted == null)) {
            this.DisconectTellNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisconectTellNoOperationCompleted);
        }
        this.InvokeAsync("DisconectTellNo", new object[] {
                    FullPhoneNo,
                    CuaseID}, this.DisconectTellNoOperationCompleted, userState);
    }
    
    private void OnDisconectTellNoOperationCompleted(object arg) {
        if ((this.DisconectTellNoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DisconectTellNoCompleted(this, new DisconectTellNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConnectTellNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool ConnectTellNo(string FullPhoneNo, int CuaseID) {
        object[] results = this.Invoke("ConnectTellNo", new object[] {
                    FullPhoneNo,
                    CuaseID});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginConnectTellNo(string FullPhoneNo, int CuaseID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ConnectTellNo", new object[] {
                    FullPhoneNo,
                    CuaseID}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndConnectTellNo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void ConnectTellNoAsync(string FullPhoneNo, int CuaseID) {
        this.ConnectTellNoAsync(FullPhoneNo, CuaseID, null);
    }
    
    /// <remarks/>
    public void ConnectTellNoAsync(string FullPhoneNo, int CuaseID, object userState) {
        if ((this.ConnectTellNoOperationCompleted == null)) {
            this.ConnectTellNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectTellNoOperationCompleted);
        }
        this.InvokeAsync("ConnectTellNo", new object[] {
                    FullPhoneNo,
                    CuaseID}, this.ConnectTellNoOperationCompleted, userState);
    }
    
    private void OnConnectTellNoOperationCompleted(object arg) {
        if ((this.ConnectTellNoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ConnectTellNoCompleted(this, new ConnectTellNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCounter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public LastCounters GetCounter(string FullPhoneNo, string UserName, string Password) {
        object[] results = this.Invoke("GetCounter", new object[] {
                    FullPhoneNo,
                    UserName,
                    Password});
        return ((LastCounters)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCounter(string FullPhoneNo, string UserName, string Password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCounter", new object[] {
                    FullPhoneNo,
                    UserName,
                    Password}, callback, asyncState);
    }
    
    /// <remarks/>
    public LastCounters EndGetCounter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((LastCounters)(results[0]));
    }
    
    /// <remarks/>
    public void GetCounterAsync(string FullPhoneNo, string UserName, string Password) {
        this.GetCounterAsync(FullPhoneNo, UserName, Password, null);
    }
    
    /// <remarks/>
    public void GetCounterAsync(string FullPhoneNo, string UserName, string Password, object userState) {
        if ((this.GetCounterOperationCompleted == null)) {
            this.GetCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCounterOperationCompleted);
        }
        this.InvokeAsync("GetCounter", new object[] {
                    FullPhoneNo,
                    UserName,
                    Password}, this.GetCounterOperationCompleted, userState);
    }
    
    private void OnGetCounterOperationCompleted(object arg) {
        if ((this.GetCounterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCounterCompleted(this, new GetCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class V_LastDebtInfo {
    
    private string stringPhoneNumberField;
    
    private double payAmountField;
    
    private double lastdebtField;
    
    private System.DateTime dateTimePaymentDateField;
    
    /// <remarks/>
    public string StringPhoneNumber {
        get {
            return this.stringPhoneNumberField;
        }
        set {
            this.stringPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public double PayAmount {
        get {
            return this.payAmountField;
        }
        set {
            this.payAmountField = value;
        }
    }
    
    /// <remarks/>
    public double Lastdebt {
        get {
            return this.lastdebtField;
        }
        set {
            this.lastdebtField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimePaymentDate {
        get {
            return this.dateTimePaymentDateField;
        }
        set {
            this.dateTimePaymentDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class LastCounters {
    
    private string stringPhoneNumberField;
    
    private double intraCityCostField;
    
    private double extraCityCostField;
    
    private double internationalCostField;
    
    private System.DateTime calculationaDateField;
    
    /// <remarks/>
    public string StringPhoneNumber {
        get {
            return this.stringPhoneNumberField;
        }
        set {
            this.stringPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public double IntraCityCost {
        get {
            return this.intraCityCostField;
        }
        set {
            this.intraCityCostField = value;
        }
    }
    
    /// <remarks/>
    public double ExtraCityCost {
        get {
            return this.extraCityCostField;
        }
        set {
            this.extraCityCostField = value;
        }
    }
    
    /// <remarks/>
    public double InternationalCost {
        get {
            return this.internationalCostField;
        }
        set {
            this.internationalCostField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CalculationaDate {
        get {
            return this.calculationaDateField;
        }
        set {
            this.calculationaDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetV_LastDebtCompletedEventHandler(object sender, GetV_LastDebtCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetV_LastDebtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetV_LastDebtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public V_LastDebtInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((V_LastDebtInfo)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DisconectTellNoCompletedEventHandler(object sender, DisconectTellNoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DisconectTellNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DisconectTellNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void ConnectTellNoCompletedEventHandler(object sender, ConnectTellNoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ConnectTellNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ConnectTellNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetCounterCompletedEventHandler(object sender, GetCounterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public LastCounters Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((LastCounters)(this.results[0]));
        }
    }
}
