--INSERT INTO [Resource]
--(ParentID,NAME,Description,Type)
--VALUES
--(
--	1,'RoleList.AssignWebServiceMethodToRole',N'انتساب دسترسی به متدهای وب سرویس',0
--)

--insert into RoleResource
--(
--	RoleID,ResourceID,IsEditable
--)
--values
--(
--	1,36,0
--)