--13950207 - 0919
--سرور 14
use CRM;

--INSERT INTO WebService
--(
--	Name
--)
--VALUES
--('TelephoneInfo'),
--('ChangeTelephoneInfo'),
--('CityInfo'),
--('CenterInfo'),
--('RequestTypeInfo'),
--('TelephoneType'),
--('TelephoneGroupType'),
--('CauseOfCut'),
--('GetPAPInstallRequestCount'),
--('GetPAPDischargeRequestCount'),
--('GetPAPExchangeRequestCount'),
--('GetFeasibilityRequest'),
--('SaveInstallRequest'),
--('SaveDischargeRequest'),
--('SaveExchangeRequest'),
--('FollowRequest')
--CREATE UNIQUE NONCLUSTERED INDEX IX_WebService_Name ON WebService (Name)
