-- SELECT  CCen.ID  as CENTERID, TI.[TEL_NUMBER] , BB.[BOOKHT_ID],ET.ETS_ID , TI.FI_CODE

 select *
into #ETES
from
(
select ROW_NUMBER() OVER (PARTITION BY FI_CODE ORDER BY case when [STATUS] = 2 then 1 else 0 end DESC) AS RN 
       ,*
from  [ORACLECRM]..[SCOTT].[ETESALI]
) as ET
where ET.RN = 1



select *
into #VBO
from
(
select ROW_NUMBER() OVER (PARTITION BY FI_CODE  ORDER BY case when [STATUS] = 2 then 1 else 0 end DESC) AS RN ,* 
from [ORACLECRM]..[SCOTT].[V_BOOKHT]
) as VB
where VB.RN = 1

SELECT  CCen.ID  as CENTERID, TI.[TEL_NUMBER] , BB.[BOOKHT_ID],ET.ETS_ID , TI.FI_CODE
FROM 
[ORACLECRM]..[SCOTT].[BASE_BOOKHT] AS BB 
JOIN #VBO AS VB ON  BB.[BOOKHT_ID] = VB.[BOOKHT_ID]
JOIN [ORACLECRM]..[SCOTT].[TELEPHONEINFORMATION] AS TI ON TI.[FI_CODE] = VB.[FI_CODE] 
JOIN #ETES AS ET ON ET.FI_CODE = TI.FI_CODE
JOIN [ORACLECRM]..[SCOTT].[CENTER] AS CEN ON TI.CENTER_CODE = CEN.CEN_CODE
JOIN CRM.dbo.Center as CCen ON CCen.CenterCode = CEN.CEN_CODE
JOIN [ORACLECRM]..[SCOTT].[CITY] AS CI ON CEN.[CI_CODE] = CI.[CI_CODE]
where BB.BOOKHT_TYPE = 27 