
namespace CaseManagement.StimulReport {
    export interface ActivityReportRow {
        Id?: number;
        RequestId?: number;
        ProvinceId?: number;
        ActivityId?: number;
        DelayCost?: number;
        YearCost?: number;
        LeakCost?: number;
        ConfirmDelayCost?: number;
        ConfirmYearCost?: number;
        ConfirmCost?: number;
        ProgramCost?: number;
        Percent?: string;
        CreatedUserId?: number;
        CreatedDate?: string;
        DiscoverLeakDate?: string;
        DiscoverLeakDateShamsi?: string;
        EndDate?: string;
        ConfirmUserId?: number;
        ActionId?: number;
        RequestId2?: number;
        RequestProvinceId?: number;
        RequestActivityId?: number;
        RequestCycleId?: number;
        RequestCustomerEffectId?: number;
        RequestOrganizationEffectId?: number;
        RequestRiskLevelId?: number;
        RequestIncomeFlowId?: number;
        RequestCount?: number;
        RequestCycleCost?: number;
        RequestFactor?: number;
        RequestDelayedCost?: number;
        RequestYearCost?: number;
        RequestAccessibleCost?: number;
        RequestInaccessibleCost?: number;
        RequestFinancial?: number;
        RequestLeakDate?: string;
        RequestDiscoverLeakDate?: string;
        RequestDiscoverLeakDateShamsi?: string;
        RequestEventDescription?: string;
        RequestMainReason?: string;
        RequestCorrectionOperation?: string;
        RequestAvoidRepeatingOperation?: string;
        RequestCreatedUserId?: number;
        RequestCreatedDate?: string;
        RequestCreatedDateShamsi?: string;
        RequestModifiedUserId?: number;
        RequestModifiedDate?: string;
        RequestIsDeleted?: boolean;
        RequestDeletedUserId?: number;
        RequestDeletedDate?: string;
        RequestEndDate?: string;
        RequestStatusId?: number;
        RequestActionId?: number;
        ProvinceName?: string;
        ProvinceEnglishName?: string;
        ProvinceManagerName?: string;
        ProvinceLetterNo?: string;
        ProvincePmoLevelId?: number;
        ProvinceInstallDate?: string;
        ProvinceCreatedUserId?: number;
        ProvinceCreatedDate?: string;
        ProvinceModifiedUserId?: number;
        ProvinceModifiedDate?: string;
        ProvinceIsDeleted?: boolean;
        ProvinceDeletedUserId?: number;
        ProvinceDeletedDate?: string;
        ActivityCode?: number;
        ActivityName?: string;
        ActivityEnglishName?: string;
        ActivityObjective?: string;
        ActivityEnglishObjective?: string;
        ActivityCreatedUserId?: number;
        ActivityCreatedDate?: string;
        ActivityModifiedUserId?: number;
        ActivityModifiedDate?: string;
        ActivityIsDeleted?: boolean;
        ActivityDeletedUserId?: number;
        ActivityDeletedDate?: string;
        ActivityGroupId?: number;
        ActivityRepeatTermId?: number;
        ActivityKeyCheckArea?: string;
        ActivityDataSource?: string;
        ActivityMethodology?: string;
        ActivityKeyFocus?: string;
        ActivityAction?: string;
        ActivityKpi?: string;
    }

    export namespace ActivityReportRow {
        export const idProperty = 'Id';
        export const nameProperty = 'Percent';
        export const localTextPrefix = 'StimulReport.ActivityReport';

        export namespace Fields {
            export declare const Id;
            export declare const RequestId;
            export declare const ProvinceId;
            export declare const ActivityId;
            export declare const DelayCost;
            export declare const YearCost;
            export declare const LeakCost;
            export declare const ConfirmDelayCost;
            export declare const ConfirmYearCost;
            export declare const ConfirmCost;
            export declare const ProgramCost;
            export declare const Percent;
            export declare const CreatedUserId;
            export declare const CreatedDate;
            export declare const DiscoverLeakDate;
            export declare const DiscoverLeakDateShamsi;
            export declare const EndDate;
            export declare const ConfirmUserId;
            export declare const ActionId;
            export declare const RequestId2: string;
            export declare const RequestProvinceId: string;
            export declare const RequestActivityId: string;
            export declare const RequestCycleId: string;
            export declare const RequestCustomerEffectId: string;
            export declare const RequestOrganizationEffectId: string;
            export declare const RequestRiskLevelId: string;
            export declare const RequestIncomeFlowId: string;
            export declare const RequestCount: string;
            export declare const RequestCycleCost: string;
            export declare const RequestFactor: string;
            export declare const RequestDelayedCost: string;
            export declare const RequestYearCost: string;
            export declare const RequestAccessibleCost: string;
            export declare const RequestInaccessibleCost: string;
            export declare const RequestFinancial: string;
            export declare const RequestLeakDate: string;
            export declare const RequestDiscoverLeakDate: string;
            export declare const RequestDiscoverLeakDateShamsi: string;
            export declare const RequestEventDescription: string;
            export declare const RequestMainReason: string;
            export declare const RequestCorrectionOperation: string;
            export declare const RequestAvoidRepeatingOperation: string;
            export declare const RequestCreatedUserId: string;
            export declare const RequestCreatedDate: string;
            export declare const RequestCreatedDateShamsi: string;
            export declare const RequestModifiedUserId: string;
            export declare const RequestModifiedDate: string;
            export declare const RequestIsDeleted: string;
            export declare const RequestDeletedUserId: string;
            export declare const RequestDeletedDate: string;
            export declare const RequestEndDate: string;
            export declare const RequestStatusId: string;
            export declare const RequestActionId: string;
            export declare const ProvinceName: string;
            export declare const ProvinceEnglishName: string;
            export declare const ProvinceManagerName: string;
            export declare const ProvinceLetterNo: string;
            export declare const ProvincePmoLevelId: string;
            export declare const ProvinceInstallDate: string;
            export declare const ProvinceCreatedUserId: string;
            export declare const ProvinceCreatedDate: string;
            export declare const ProvinceModifiedUserId: string;
            export declare const ProvinceModifiedDate: string;
            export declare const ProvinceIsDeleted: string;
            export declare const ProvinceDeletedUserId: string;
            export declare const ProvinceDeletedDate: string;
            export declare const ActivityCode: string;
            export declare const ActivityName: string;
            export declare const ActivityEnglishName: string;
            export declare const ActivityObjective: string;
            export declare const ActivityEnglishObjective: string;
            export declare const ActivityCreatedUserId: string;
            export declare const ActivityCreatedDate: string;
            export declare const ActivityModifiedUserId: string;
            export declare const ActivityModifiedDate: string;
            export declare const ActivityIsDeleted: string;
            export declare const ActivityDeletedUserId: string;
            export declare const ActivityDeletedDate: string;
            export declare const ActivityGroupId: string;
            export declare const ActivityRepeatTermId: string;
            export declare const ActivityKeyCheckArea: string;
            export declare const ActivityDataSource: string;
            export declare const ActivityMethodology: string;
            export declare const ActivityKeyFocus: string;
            export declare const ActivityAction: string;
            export declare const ActivityKpi: string;
        }

        ['Id', 'RequestId', 'ProvinceId', 'ActivityId', 'DelayCost', 'YearCost', 'LeakCost', 'ConfirmDelayCost', 'ConfirmYearCost', 'ConfirmCost', 'ProgramCost', 'Percent', 'CreatedUserId', 'CreatedDate', 'DiscoverLeakDate', 'DiscoverLeakDateShamsi', 'EndDate', 'ConfirmUserId', 'ActionId', 'RequestId2', 'RequestProvinceId', 'RequestActivityId', 'RequestCycleId', 'RequestCustomerEffectId', 'RequestOrganizationEffectId', 'RequestRiskLevelId', 'RequestIncomeFlowId', 'RequestCount', 'RequestCycleCost', 'RequestFactor', 'RequestDelayedCost', 'RequestYearCost', 'RequestAccessibleCost', 'RequestInaccessibleCost', 'RequestFinancial', 'RequestLeakDate', 'RequestDiscoverLeakDate', 'RequestDiscoverLeakDateShamsi', 'RequestEventDescription', 'RequestMainReason', 'RequestCorrectionOperation', 'RequestAvoidRepeatingOperation', 'RequestCreatedUserId', 'RequestCreatedDate', 'RequestCreatedDateShamsi', 'RequestModifiedUserId', 'RequestModifiedDate', 'RequestIsDeleted', 'RequestDeletedUserId', 'RequestDeletedDate', 'RequestEndDate', 'RequestStatusId', 'RequestActionId', 'ProvinceName', 'ProvinceEnglishName', 'ProvinceManagerName', 'ProvinceLetterNo', 'ProvincePmoLevelId', 'ProvinceInstallDate', 'ProvinceCreatedUserId', 'ProvinceCreatedDate', 'ProvinceModifiedUserId', 'ProvinceModifiedDate', 'ProvinceIsDeleted', 'ProvinceDeletedUserId', 'ProvinceDeletedDate', 'ActivityCode', 'ActivityName', 'ActivityEnglishName', 'ActivityObjective', 'ActivityEnglishObjective', 'ActivityCreatedUserId', 'ActivityCreatedDate', 'ActivityModifiedUserId', 'ActivityModifiedDate', 'ActivityIsDeleted', 'ActivityDeletedUserId', 'ActivityDeletedDate', 'ActivityGroupId', 'ActivityRepeatTermId', 'ActivityKeyCheckArea', 'ActivityDataSource', 'ActivityMethodology', 'ActivityKeyFocus', 'ActivityAction', 'ActivityKpi'].forEach(x => (<any>Fields)[x] = x);
    }
}

