//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback ExecuteSelectQueryOperationCompleted;
    
    private System.Threading.SendOrPostCallback Get_Debt_CountOperationCompleted;
    
    private System.Threading.SendOrPostCallback Phone_Is_PCMOperationCompleted;
    
    private System.Threading.SendOrPostCallback Phone_Exist_In_Post_PCMOperationCompleted;
    
    private System.Threading.SendOrPostCallback Phone_CUSTOMER_BOOKHTINFOOperationCompleted;
    
    private System.Threading.SendOrPostCallback Is_Phone_ExistOperationCompleted;
    
    private System.Threading.SendOrPostCallback TelDissectionStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback Tel_BookhtOperationCompleted;
    
    private System.Threading.SendOrPostCallback Tel_Have_ADSl_PortOperationCompleted;
    
    private System.Threading.SendOrPostCallback Get_Costumer_AddressOperationCompleted;
    
    private System.Threading.SendOrPostCallback Get_Costumer_118_InfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Get_Disconnected_PhoneOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInformationForPhoneOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInformationForNationalCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInformationForPhoneV2OperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInformationByNationalCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_MobileNumber_By_FI_CODEOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetPCMInformationOperationCompleted;
    
    private System.Threading.SendOrPostCallback Get_ChangesOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://elkaws.tcsem.ir:5555/CRM_WBS/SE_CRM.asmx";
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event ExecuteSelectQueryCompletedEventHandler ExecuteSelectQueryCompleted;
    
    /// <remarks/>
    public event Get_Debt_CountCompletedEventHandler Get_Debt_CountCompleted;
    
    /// <remarks/>
    public event Phone_Is_PCMCompletedEventHandler Phone_Is_PCMCompleted;
    
    /// <remarks/>
    public event Phone_Exist_In_Post_PCMCompletedEventHandler Phone_Exist_In_Post_PCMCompleted;
    
    /// <remarks/>
    public event Phone_CUSTOMER_BOOKHTINFOCompletedEventHandler Phone_CUSTOMER_BOOKHTINFOCompleted;
    
    /// <remarks/>
    public event Is_Phone_ExistCompletedEventHandler Is_Phone_ExistCompleted;
    
    /// <remarks/>
    public event TelDissectionStatusCompletedEventHandler TelDissectionStatusCompleted;
    
    /// <remarks/>
    public event Tel_BookhtCompletedEventHandler Tel_BookhtCompleted;
    
    /// <remarks/>
    public event Tel_Have_ADSl_PortCompletedEventHandler Tel_Have_ADSl_PortCompleted;
    
    /// <remarks/>
    public event Get_Costumer_AddressCompletedEventHandler Get_Costumer_AddressCompleted;
    
    /// <remarks/>
    public event Get_Costumer_118_InfoCompletedEventHandler Get_Costumer_118_InfoCompleted;
    
    /// <remarks/>
    public event Get_Disconnected_PhoneCompletedEventHandler Get_Disconnected_PhoneCompleted;
    
    /// <remarks/>
    public event GetInformationForPhoneCompletedEventHandler GetInformationForPhoneCompleted;
    
    /// <remarks/>
    public event GetInformationForNationalCodeCompletedEventHandler GetInformationForNationalCodeCompleted;
    
    /// <remarks/>
    public event GetInformationForPhoneV2CompletedEventHandler GetInformationForPhoneV2Completed;
    
    /// <remarks/>
    public event GetInformationByNationalCodeCompletedEventHandler GetInformationByNationalCodeCompleted;
    
    /// <remarks/>
    public event Update_MobileNumber_By_FI_CODECompletedEventHandler Update_MobileNumber_By_FI_CODECompleted;
    
    /// <remarks/>
    public event GetPCMInformationCompletedEventHandler GetPCMInformationCompleted;
    
    /// <remarks/>
    public event Get_ChangesCompletedEventHandler Get_ChangesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteSelectQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet ExecuteSelectQuery(string Username, string Password, string Query, string ProviderName) {
        object[] results = this.Invoke("ExecuteSelectQuery", new object[] {
                    Username,
                    Password,
                    Query,
                    ProviderName});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginExecuteSelectQuery(string Username, string Password, string Query, string ProviderName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ExecuteSelectQuery", new object[] {
                    Username,
                    Password,
                    Query,
                    ProviderName}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndExecuteSelectQuery(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void ExecuteSelectQueryAsync(string Username, string Password, string Query, string ProviderName) {
        this.ExecuteSelectQueryAsync(Username, Password, Query, ProviderName, null);
    }
    
    /// <remarks/>
    public void ExecuteSelectQueryAsync(string Username, string Password, string Query, string ProviderName, object userState) {
        if ((this.ExecuteSelectQueryOperationCompleted == null)) {
            this.ExecuteSelectQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteSelectQueryOperationCompleted);
        }
        this.InvokeAsync("ExecuteSelectQuery", new object[] {
                    Username,
                    Password,
                    Query,
                    ProviderName}, this.ExecuteSelectQueryOperationCompleted, userState);
    }
    
    private void OnExecuteSelectQueryOperationCompleted(object arg) {
        if ((this.ExecuteSelectQueryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ExecuteSelectQueryCompleted(this, new ExecuteSelectQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Debt_Count", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet Get_Debt_Count(string Username, string Password) {
        object[] results = this.Invoke("Get_Debt_Count", new object[] {
                    Username,
                    Password});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGet_Debt_Count(string Username, string Password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Get_Debt_Count", new object[] {
                    Username,
                    Password}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGet_Debt_Count(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void Get_Debt_CountAsync(string Username, string Password) {
        this.Get_Debt_CountAsync(Username, Password, null);
    }
    
    /// <remarks/>
    public void Get_Debt_CountAsync(string Username, string Password, object userState) {
        if ((this.Get_Debt_CountOperationCompleted == null)) {
            this.Get_Debt_CountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Debt_CountOperationCompleted);
        }
        this.InvokeAsync("Get_Debt_Count", new object[] {
                    Username,
                    Password}, this.Get_Debt_CountOperationCompleted, userState);
    }
    
    private void OnGet_Debt_CountOperationCompleted(object arg) {
        if ((this.Get_Debt_CountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Get_Debt_CountCompleted(this, new Get_Debt_CountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Phone_Is_PCM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Phone_Is_PCM(string Telephone) {
        object[] results = this.Invoke("Phone_Is_PCM", new object[] {
                    Telephone});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPhone_Is_PCM(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Phone_Is_PCM", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndPhone_Is_PCM(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void Phone_Is_PCMAsync(string Telephone) {
        this.Phone_Is_PCMAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Phone_Is_PCMAsync(string Telephone, object userState) {
        if ((this.Phone_Is_PCMOperationCompleted == null)) {
            this.Phone_Is_PCMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhone_Is_PCMOperationCompleted);
        }
        this.InvokeAsync("Phone_Is_PCM", new object[] {
                    Telephone}, this.Phone_Is_PCMOperationCompleted, userState);
    }
    
    private void OnPhone_Is_PCMOperationCompleted(object arg) {
        if ((this.Phone_Is_PCMCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Phone_Is_PCMCompleted(this, new Phone_Is_PCMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Phone_Exist_In_Post_PCM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Phone_Exist_In_Post_PCM(string Telephone) {
        object[] results = this.Invoke("Phone_Exist_In_Post_PCM", new object[] {
                    Telephone});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPhone_Exist_In_Post_PCM(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Phone_Exist_In_Post_PCM", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndPhone_Exist_In_Post_PCM(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void Phone_Exist_In_Post_PCMAsync(string Telephone) {
        this.Phone_Exist_In_Post_PCMAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Phone_Exist_In_Post_PCMAsync(string Telephone, object userState) {
        if ((this.Phone_Exist_In_Post_PCMOperationCompleted == null)) {
            this.Phone_Exist_In_Post_PCMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhone_Exist_In_Post_PCMOperationCompleted);
        }
        this.InvokeAsync("Phone_Exist_In_Post_PCM", new object[] {
                    Telephone}, this.Phone_Exist_In_Post_PCMOperationCompleted, userState);
    }
    
    private void OnPhone_Exist_In_Post_PCMOperationCompleted(object arg) {
        if ((this.Phone_Exist_In_Post_PCMCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Phone_Exist_In_Post_PCMCompleted(this, new Phone_Exist_In_Post_PCMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Phone_CUSTOMER_BOOKHTINFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Phone_CUSTOMER_BOOKHTINFO(string Telephone) {
        object[] results = this.Invoke("Phone_CUSTOMER_BOOKHTINFO", new object[] {
                    Telephone});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPhone_CUSTOMER_BOOKHTINFO(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Phone_CUSTOMER_BOOKHTINFO", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndPhone_CUSTOMER_BOOKHTINFO(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Phone_CUSTOMER_BOOKHTINFOAsync(string Telephone) {
        this.Phone_CUSTOMER_BOOKHTINFOAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Phone_CUSTOMER_BOOKHTINFOAsync(string Telephone, object userState) {
        if ((this.Phone_CUSTOMER_BOOKHTINFOOperationCompleted == null)) {
            this.Phone_CUSTOMER_BOOKHTINFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhone_CUSTOMER_BOOKHTINFOOperationCompleted);
        }
        this.InvokeAsync("Phone_CUSTOMER_BOOKHTINFO", new object[] {
                    Telephone}, this.Phone_CUSTOMER_BOOKHTINFOOperationCompleted, userState);
    }
    
    private void OnPhone_CUSTOMER_BOOKHTINFOOperationCompleted(object arg) {
        if ((this.Phone_CUSTOMER_BOOKHTINFOCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Phone_CUSTOMER_BOOKHTINFOCompleted(this, new Phone_CUSTOMER_BOOKHTINFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Is_Phone_Exist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Is_Phone_Exist(string Telephone) {
        object[] results = this.Invoke("Is_Phone_Exist", new object[] {
                    Telephone});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginIs_Phone_Exist(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Is_Phone_Exist", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndIs_Phone_Exist(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void Is_Phone_ExistAsync(string Telephone) {
        this.Is_Phone_ExistAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Is_Phone_ExistAsync(string Telephone, object userState) {
        if ((this.Is_Phone_ExistOperationCompleted == null)) {
            this.Is_Phone_ExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIs_Phone_ExistOperationCompleted);
        }
        this.InvokeAsync("Is_Phone_Exist", new object[] {
                    Telephone}, this.Is_Phone_ExistOperationCompleted, userState);
    }
    
    private void OnIs_Phone_ExistOperationCompleted(object arg) {
        if ((this.Is_Phone_ExistCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Is_Phone_ExistCompleted(this, new Is_Phone_ExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TelDissectionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool TelDissectionStatus(string Telephone) {
        object[] results = this.Invoke("TelDissectionStatus", new object[] {
                    Telephone});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTelDissectionStatus(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("TelDissectionStatus", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndTelDissectionStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void TelDissectionStatusAsync(string Telephone) {
        this.TelDissectionStatusAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void TelDissectionStatusAsync(string Telephone, object userState) {
        if ((this.TelDissectionStatusOperationCompleted == null)) {
            this.TelDissectionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTelDissectionStatusOperationCompleted);
        }
        this.InvokeAsync("TelDissectionStatus", new object[] {
                    Telephone}, this.TelDissectionStatusOperationCompleted, userState);
    }
    
    private void OnTelDissectionStatusOperationCompleted(object arg) {
        if ((this.TelDissectionStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.TelDissectionStatusCompleted(this, new TelDissectionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Tel_Bookht", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Tel_Bookht(string Telephone) {
        object[] results = this.Invoke("Tel_Bookht", new object[] {
                    Telephone});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTel_Bookht(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Tel_Bookht", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndTel_Bookht(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Tel_BookhtAsync(string Telephone) {
        this.Tel_BookhtAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Tel_BookhtAsync(string Telephone, object userState) {
        if ((this.Tel_BookhtOperationCompleted == null)) {
            this.Tel_BookhtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTel_BookhtOperationCompleted);
        }
        this.InvokeAsync("Tel_Bookht", new object[] {
                    Telephone}, this.Tel_BookhtOperationCompleted, userState);
    }
    
    private void OnTel_BookhtOperationCompleted(object arg) {
        if ((this.Tel_BookhtCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Tel_BookhtCompleted(this, new Tel_BookhtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Tel_Have_ADSl_Port", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Tel_Have_ADSl_Port(string Telephone) {
        object[] results = this.Invoke("Tel_Have_ADSl_Port", new object[] {
                    Telephone});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTel_Have_ADSl_Port(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Tel_Have_ADSl_Port", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndTel_Have_ADSl_Port(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void Tel_Have_ADSl_PortAsync(string Telephone) {
        this.Tel_Have_ADSl_PortAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Tel_Have_ADSl_PortAsync(string Telephone, object userState) {
        if ((this.Tel_Have_ADSl_PortOperationCompleted == null)) {
            this.Tel_Have_ADSl_PortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTel_Have_ADSl_PortOperationCompleted);
        }
        this.InvokeAsync("Tel_Have_ADSl_Port", new object[] {
                    Telephone}, this.Tel_Have_ADSl_PortOperationCompleted, userState);
    }
    
    private void OnTel_Have_ADSl_PortOperationCompleted(object arg) {
        if ((this.Tel_Have_ADSl_PortCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Tel_Have_ADSl_PortCompleted(this, new Tel_Have_ADSl_PortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Costumer_Address", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Get_Costumer_Address(string Telephone) {
        object[] results = this.Invoke("Get_Costumer_Address", new object[] {
                    Telephone});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGet_Costumer_Address(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Get_Costumer_Address", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGet_Costumer_Address(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Get_Costumer_AddressAsync(string Telephone) {
        this.Get_Costumer_AddressAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Get_Costumer_AddressAsync(string Telephone, object userState) {
        if ((this.Get_Costumer_AddressOperationCompleted == null)) {
            this.Get_Costumer_AddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Costumer_AddressOperationCompleted);
        }
        this.InvokeAsync("Get_Costumer_Address", new object[] {
                    Telephone}, this.Get_Costumer_AddressOperationCompleted, userState);
    }
    
    private void OnGet_Costumer_AddressOperationCompleted(object arg) {
        if ((this.Get_Costumer_AddressCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Get_Costumer_AddressCompleted(this, new Get_Costumer_AddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Costumer_118_Info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Get_Costumer_118_Info(string Telephone) {
        object[] results = this.Invoke("Get_Costumer_118_Info", new object[] {
                    Telephone});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGet_Costumer_118_Info(string Telephone, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Get_Costumer_118_Info", new object[] {
                    Telephone}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGet_Costumer_118_Info(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Get_Costumer_118_InfoAsync(string Telephone) {
        this.Get_Costumer_118_InfoAsync(Telephone, null);
    }
    
    /// <remarks/>
    public void Get_Costumer_118_InfoAsync(string Telephone, object userState) {
        if ((this.Get_Costumer_118_InfoOperationCompleted == null)) {
            this.Get_Costumer_118_InfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Costumer_118_InfoOperationCompleted);
        }
        this.InvokeAsync("Get_Costumer_118_Info", new object[] {
                    Telephone}, this.Get_Costumer_118_InfoOperationCompleted, userState);
    }
    
    private void OnGet_Costumer_118_InfoOperationCompleted(object arg) {
        if ((this.Get_Costumer_118_InfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Get_Costumer_118_InfoCompleted(this, new Get_Costumer_118_InfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Disconnected_Phone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet Get_Disconnected_Phone(string Username, string Password) {
        object[] results = this.Invoke("Get_Disconnected_Phone", new object[] {
                    Username,
                    Password});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGet_Disconnected_Phone(string Username, string Password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Get_Disconnected_Phone", new object[] {
                    Username,
                    Password}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGet_Disconnected_Phone(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void Get_Disconnected_PhoneAsync(string Username, string Password) {
        this.Get_Disconnected_PhoneAsync(Username, Password, null);
    }
    
    /// <remarks/>
    public void Get_Disconnected_PhoneAsync(string Username, string Password, object userState) {
        if ((this.Get_Disconnected_PhoneOperationCompleted == null)) {
            this.Get_Disconnected_PhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Disconnected_PhoneOperationCompleted);
        }
        this.InvokeAsync("Get_Disconnected_Phone", new object[] {
                    Username,
                    Password}, this.Get_Disconnected_PhoneOperationCompleted, userState);
    }
    
    private void OnGet_Disconnected_PhoneOperationCompleted(object arg) {
        if ((this.Get_Disconnected_PhoneCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Get_Disconnected_PhoneCompleted(this, new Get_Disconnected_PhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInformationForPhone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetInformationForPhone(string Username, string Password, string PhoneNo) {
        object[] results = this.Invoke("GetInformationForPhone", new object[] {
                    Username,
                    Password,
                    PhoneNo});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInformationForPhone(string Username, string Password, string PhoneNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInformationForPhone", new object[] {
                    Username,
                    Password,
                    PhoneNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetInformationForPhone(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetInformationForPhoneAsync(string Username, string Password, string PhoneNo) {
        this.GetInformationForPhoneAsync(Username, Password, PhoneNo, null);
    }
    
    /// <remarks/>
    public void GetInformationForPhoneAsync(string Username, string Password, string PhoneNo, object userState) {
        if ((this.GetInformationForPhoneOperationCompleted == null)) {
            this.GetInformationForPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInformationForPhoneOperationCompleted);
        }
        this.InvokeAsync("GetInformationForPhone", new object[] {
                    Username,
                    Password,
                    PhoneNo}, this.GetInformationForPhoneOperationCompleted, userState);
    }
    
    private void OnGetInformationForPhoneOperationCompleted(object arg) {
        if ((this.GetInformationForPhoneCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInformationForPhoneCompleted(this, new GetInformationForPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInformationForNationalCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetInformationForNationalCode(string Username, string Password, string NationalCode) {
        object[] results = this.Invoke("GetInformationForNationalCode", new object[] {
                    Username,
                    Password,
                    NationalCode});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInformationForNationalCode(string Username, string Password, string NationalCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInformationForNationalCode", new object[] {
                    Username,
                    Password,
                    NationalCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetInformationForNationalCode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetInformationForNationalCodeAsync(string Username, string Password, string NationalCode) {
        this.GetInformationForNationalCodeAsync(Username, Password, NationalCode, null);
    }
    
    /// <remarks/>
    public void GetInformationForNationalCodeAsync(string Username, string Password, string NationalCode, object userState) {
        if ((this.GetInformationForNationalCodeOperationCompleted == null)) {
            this.GetInformationForNationalCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInformationForNationalCodeOperationCompleted);
        }
        this.InvokeAsync("GetInformationForNationalCode", new object[] {
                    Username,
                    Password,
                    NationalCode}, this.GetInformationForNationalCodeOperationCompleted, userState);
    }
    
    private void OnGetInformationForNationalCodeOperationCompleted(object arg) {
        if ((this.GetInformationForNationalCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInformationForNationalCodeCompleted(this, new GetInformationForNationalCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInformationForPhoneV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetInformationForPhoneV2(string Username, string Password, string PhoneNo) {
        object[] results = this.Invoke("GetInformationForPhoneV2", new object[] {
                    Username,
                    Password,
                    PhoneNo});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInformationForPhoneV2(string Username, string Password, string PhoneNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInformationForPhoneV2", new object[] {
                    Username,
                    Password,
                    PhoneNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetInformationForPhoneV2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetInformationForPhoneV2Async(string Username, string Password, string PhoneNo) {
        this.GetInformationForPhoneV2Async(Username, Password, PhoneNo, null);
    }
    
    /// <remarks/>
    public void GetInformationForPhoneV2Async(string Username, string Password, string PhoneNo, object userState) {
        if ((this.GetInformationForPhoneV2OperationCompleted == null)) {
            this.GetInformationForPhoneV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInformationForPhoneV2OperationCompleted);
        }
        this.InvokeAsync("GetInformationForPhoneV2", new object[] {
                    Username,
                    Password,
                    PhoneNo}, this.GetInformationForPhoneV2OperationCompleted, userState);
    }
    
    private void OnGetInformationForPhoneV2OperationCompleted(object arg) {
        if ((this.GetInformationForPhoneV2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInformationForPhoneV2Completed(this, new GetInformationForPhoneV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInformationByNationalCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetInformationByNationalCode(string Username, string Password, string NationalCode) {
        object[] results = this.Invoke("GetInformationByNationalCode", new object[] {
                    Username,
                    Password,
                    NationalCode});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInformationByNationalCode(string Username, string Password, string NationalCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInformationByNationalCode", new object[] {
                    Username,
                    Password,
                    NationalCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetInformationByNationalCode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetInformationByNationalCodeAsync(string Username, string Password, string NationalCode) {
        this.GetInformationByNationalCodeAsync(Username, Password, NationalCode, null);
    }
    
    /// <remarks/>
    public void GetInformationByNationalCodeAsync(string Username, string Password, string NationalCode, object userState) {
        if ((this.GetInformationByNationalCodeOperationCompleted == null)) {
            this.GetInformationByNationalCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInformationByNationalCodeOperationCompleted);
        }
        this.InvokeAsync("GetInformationByNationalCode", new object[] {
                    Username,
                    Password,
                    NationalCode}, this.GetInformationByNationalCodeOperationCompleted, userState);
    }
    
    private void OnGetInformationByNationalCodeOperationCompleted(object arg) {
        if ((this.GetInformationByNationalCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInformationByNationalCodeCompleted(this, new GetInformationByNationalCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_MobileNumber_By_FI_CODE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int Update_MobileNumber_By_FI_CODE(string Username, string Password, string FI_CODE, string CUSTUMERTYPE, string MobileNumber) {
        object[] results = this.Invoke("Update_MobileNumber_By_FI_CODE", new object[] {
                    Username,
                    Password,
                    FI_CODE,
                    CUSTUMERTYPE,
                    MobileNumber});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_MobileNumber_By_FI_CODE(string Username, string Password, string FI_CODE, string CUSTUMERTYPE, string MobileNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_MobileNumber_By_FI_CODE", new object[] {
                    Username,
                    Password,
                    FI_CODE,
                    CUSTUMERTYPE,
                    MobileNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndUpdate_MobileNumber_By_FI_CODE(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void Update_MobileNumber_By_FI_CODEAsync(string Username, string Password, string FI_CODE, string CUSTUMERTYPE, string MobileNumber) {
        this.Update_MobileNumber_By_FI_CODEAsync(Username, Password, FI_CODE, CUSTUMERTYPE, MobileNumber, null);
    }
    
    /// <remarks/>
    public void Update_MobileNumber_By_FI_CODEAsync(string Username, string Password, string FI_CODE, string CUSTUMERTYPE, string MobileNumber, object userState) {
        if ((this.Update_MobileNumber_By_FI_CODEOperationCompleted == null)) {
            this.Update_MobileNumber_By_FI_CODEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_MobileNumber_By_FI_CODEOperationCompleted);
        }
        this.InvokeAsync("Update_MobileNumber_By_FI_CODE", new object[] {
                    Username,
                    Password,
                    FI_CODE,
                    CUSTUMERTYPE,
                    MobileNumber}, this.Update_MobileNumber_By_FI_CODEOperationCompleted, userState);
    }
    
    private void OnUpdate_MobileNumber_By_FI_CODEOperationCompleted(object arg) {
        if ((this.Update_MobileNumber_By_FI_CODECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_MobileNumber_By_FI_CODECompleted(this, new Update_MobileNumber_By_FI_CODECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPCMInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable GetPCMInformation(string Username, string Password, string PhoneNo) {
        object[] results = this.Invoke("GetPCMInformation", new object[] {
                    Username,
                    Password,
                    PhoneNo});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPCMInformation(string Username, string Password, string PhoneNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetPCMInformation", new object[] {
                    Username,
                    Password,
                    PhoneNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndGetPCMInformation(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void GetPCMInformationAsync(string Username, string Password, string PhoneNo) {
        this.GetPCMInformationAsync(Username, Password, PhoneNo, null);
    }
    
    /// <remarks/>
    public void GetPCMInformationAsync(string Username, string Password, string PhoneNo, object userState) {
        if ((this.GetPCMInformationOperationCompleted == null)) {
            this.GetPCMInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPCMInformationOperationCompleted);
        }
        this.InvokeAsync("GetPCMInformation", new object[] {
                    Username,
                    Password,
                    PhoneNo}, this.GetPCMInformationOperationCompleted, userState);
    }
    
    private void OnGetPCMInformationOperationCompleted(object arg) {
        if ((this.GetPCMInformationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPCMInformationCompleted(this, new GetPCMInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Changes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet Get_Changes(string Username, string Password, string FromDate, string ToDate, long WebServiceID, int CostTypeID) {
        object[] results = this.Invoke("Get_Changes", new object[] {
                    Username,
                    Password,
                    FromDate,
                    ToDate,
                    WebServiceID,
                    CostTypeID});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGet_Changes(string Username, string Password, string FromDate, string ToDate, long WebServiceID, int CostTypeID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Get_Changes", new object[] {
                    Username,
                    Password,
                    FromDate,
                    ToDate,
                    WebServiceID,
                    CostTypeID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGet_Changes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void Get_ChangesAsync(string Username, string Password, string FromDate, string ToDate, long WebServiceID, int CostTypeID) {
        this.Get_ChangesAsync(Username, Password, FromDate, ToDate, WebServiceID, CostTypeID, null);
    }
    
    /// <remarks/>
    public void Get_ChangesAsync(string Username, string Password, string FromDate, string ToDate, long WebServiceID, int CostTypeID, object userState) {
        if ((this.Get_ChangesOperationCompleted == null)) {
            this.Get_ChangesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ChangesOperationCompleted);
        }
        this.InvokeAsync("Get_Changes", new object[] {
                    Username,
                    Password,
                    FromDate,
                    ToDate,
                    WebServiceID,
                    CostTypeID}, this.Get_ChangesOperationCompleted, userState);
    }
    
    private void OnGet_ChangesOperationCompleted(object arg) {
        if ((this.Get_ChangesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Get_ChangesCompleted(this, new Get_ChangesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void ExecuteSelectQueryCompletedEventHandler(object sender, ExecuteSelectQueryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ExecuteSelectQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ExecuteSelectQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Get_Debt_CountCompletedEventHandler(object sender, Get_Debt_CountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Get_Debt_CountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Get_Debt_CountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Phone_Is_PCMCompletedEventHandler(object sender, Phone_Is_PCMCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Phone_Is_PCMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Phone_Is_PCMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Phone_Exist_In_Post_PCMCompletedEventHandler(object sender, Phone_Exist_In_Post_PCMCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Phone_Exist_In_Post_PCMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Phone_Exist_In_Post_PCMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Phone_CUSTOMER_BOOKHTINFOCompletedEventHandler(object sender, Phone_CUSTOMER_BOOKHTINFOCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Phone_CUSTOMER_BOOKHTINFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Phone_CUSTOMER_BOOKHTINFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Is_Phone_ExistCompletedEventHandler(object sender, Is_Phone_ExistCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Is_Phone_ExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Is_Phone_ExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void TelDissectionStatusCompletedEventHandler(object sender, TelDissectionStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TelDissectionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal TelDissectionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Tel_BookhtCompletedEventHandler(object sender, Tel_BookhtCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Tel_BookhtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Tel_BookhtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Tel_Have_ADSl_PortCompletedEventHandler(object sender, Tel_Have_ADSl_PortCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Tel_Have_ADSl_PortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Tel_Have_ADSl_PortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Get_Costumer_AddressCompletedEventHandler(object sender, Get_Costumer_AddressCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Get_Costumer_AddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Get_Costumer_AddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Get_Costumer_118_InfoCompletedEventHandler(object sender, Get_Costumer_118_InfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Get_Costumer_118_InfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Get_Costumer_118_InfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Get_Disconnected_PhoneCompletedEventHandler(object sender, Get_Disconnected_PhoneCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Get_Disconnected_PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Get_Disconnected_PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetInformationForPhoneCompletedEventHandler(object sender, GetInformationForPhoneCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInformationForPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInformationForPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetInformationForNationalCodeCompletedEventHandler(object sender, GetInformationForNationalCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInformationForNationalCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInformationForNationalCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetInformationForPhoneV2CompletedEventHandler(object sender, GetInformationForPhoneV2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInformationForPhoneV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInformationForPhoneV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetInformationByNationalCodeCompletedEventHandler(object sender, GetInformationByNationalCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInformationByNationalCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInformationByNationalCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Update_MobileNumber_By_FI_CODECompletedEventHandler(object sender, Update_MobileNumber_By_FI_CODECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_MobileNumber_By_FI_CODECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_MobileNumber_By_FI_CODECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetPCMInformationCompletedEventHandler(object sender, GetPCMInformationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPCMInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetPCMInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void Get_ChangesCompletedEventHandler(object sender, Get_ChangesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Get_ChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Get_ChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}
