  SELECT COUNT(*)
  FROM [ORACLECRM]..[SCOTT].[TELEPHONEINFORMATION] AS TI 
       JOIN  [ORACLECRM]..[SCOTT].[V_BOOKHT] AS VB ON TI.[FI_CODE] = VB.[FI_CODE]
	   JOIN  [ORACLECRM]..[SCOTT].[BASE_BOOKHT] AS BB ON VB.[BOOKHT_ID] = BB.[BOOKHT_ID]
	   JOIN  [ORACLECRM]..[SCOTT].[ETESALI] AS E ON TI.[FI_CODE] = E.[FI_CODE]
	   JOIN  [ORACLECRM]..[SCOTT].[BASE_ETESALI] AS BS ON E.[ETS_ID] = BS.[ETS_ID]
	   WHERE BB.[BOOKHT_TYPE]  IN (22,23) AND BS.[PCM_STATUS] = 0

SELECT TI.[FI_CODE]
      ,TI.[TEL_NUMBER]
	  ,BB.[BOOKHT_ID]
	  ,BB.[CEN_CODE]
      ,BB.[RADIF]
      ,BB.[TABAGHE]
      ,BB.[ETESALI]
      ,BB.[BOOKHT_TYPE]
      ,BB.[STATUS]
      ,BB.[BB_DATE]
      ,BB.[BB_HOUR]
	  ,BS.[ETS_ID]
      ,TI.[TEL_LAST_COUNTER_READ]
      ,TI.[TEL_COUNTER_START]
      ,TI.[TEL_STATUS]
      ,TI.[TEL_DATE]
      ,TI.[TEL_HOUR]
      ,TI.[CENTER_CODE]
      ,TI.[REQ_ID]
      ,VB.[STATUS]
	  ,BB.[BOOKHT_TYPE]
	  ,BB.[STATUS]
      ,BB.[CEN_CODE]
	  ,BS.[PCM_STATUS]
  FROM [ORACLECRM]..[SCOTT].[TELEPHONEINFORMATION] AS TI 
       JOIN  [ORACLECRM]..[SCOTT].[V_BOOKHT] AS VB ON TI.[FI_CODE] = VB.[FI_CODE]
	   JOIN  [ORACLECRM]..[SCOTT].[BASE_BOOKHT] AS BB ON VB.[BOOKHT_ID] = BB.[BOOKHT_ID]
	   JOIN  [ORACLECRM]..[SCOTT].[ETESALI] AS E ON TI.[FI_CODE] = E.[FI_CODE]
	   JOIN  [ORACLECRM]..[SCOTT].[BASE_ETESALI] AS BS ON E.[ETS_ID] = BS.[ETS_ID]
	  WHERE BB.[BOOKHT_TYPE] NOT IN (22,23) AND BS.[PCM_STATUS] = 0 AND 10129372 = BS.[ETS_ID]




 SELECT BS.[ETS_ID]
      ,BS.[ETS_NUM]
      ,BS.[METRAJH]
      ,BS.[PCM_STATUS]
      ,BS.[STATUS]
      ,BS.[BE_DATE]
      ,BS.[POST_ID]
      ,BS.[BE_HOUR]
  FROM [ORACLECRM]..[SCOTT].[BASE_ETESALI] as BS
  WHERE 10129372 = BS.[ETS_ID]


SELECT E.[FI_CODE]
      ,E.[ETS_ID]
      ,E.[STATUS]
      ,E.[E_DATE]
      ,E.[E_HOUR]
      ,E.[REQ_ID]
  FROM [ORACLECRM]..[SCOTT].[ETESALI] AS E
   WHERE 10129372 = E.[ETS_ID]
GO


   --  WHERE BB.[STATUS] <> VB.[STATUS] AND BB.[STATUS] <> TI.[TEL_STATUS]


  --SELECT 
  --    BB.[BOOKHT_ID]
  --    ,BB.[CEN_CODE]
  --    ,BB.[RADIF]
  --    ,BB.[TABAGHE]
  --    ,BB.[ETESALI]
  --    ,BB.[BOOKHT_TYPE]
  --    ,BB.[STATUS]
  --    ,BB.[BB_DATE]
  --    ,BB.[BB_HOUR]
--  FROM [ORACLECRM]..[SCOTT].[BASE_BOOKHT] AS BB


--SELECT VB.[BOOKHT_ID]
--      ,VB.[FI_CODE]
--      ,VB.[STATUS]
--      ,VB.[VB_DATE]
--      ,VB.[VB_HOUR]
--      ,VB.[REQ_ID]
--  FROM [ORACLECRM]..[SCOTT].[V_BOOKHT] AS VB
--GO


