//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace SOAPSendSMS
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "MessageRelayPortBinding", Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class MessageRelayService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getUserInfoOperationCompleted;

        private System.Threading.SendOrPostCallback getReceivedMessageCountOperationCompleted;

        private System.Threading.SendOrPostCallback pullReceivedMessagesOperationCompleted;

        private System.Threading.SendOrPostCallback sendMessageManyToManyOperationCompleted;

        private System.Threading.SendOrPostCallback sendMessageOneToManyOperationCompleted;

        private System.Threading.SendOrPostCallback getMessageStateOperationCompleted;

        /// <remarks/>
        public MessageRelayService()
        {
            this.Url = "http://ws.armaghan.net:8080/ws-relay/MessageRelayService";
        }

        /// <remarks/>
        public event getUserInfoCompletedEventHandler getUserInfoCompleted;

        /// <remarks/>
        public event getReceivedMessageCountCompletedEventHandler getReceivedMessageCountCompleted;

        /// <remarks/>
        public event pullReceivedMessagesCompletedEventHandler pullReceivedMessagesCompleted;

        /// <remarks/>
        public event sendMessageManyToManyCompletedEventHandler sendMessageManyToManyCompleted;

        /// <remarks/>
        public event sendMessageOneToManyCompletedEventHandler sendMessageOneToManyCompleted;

        /// <remarks/>
        public event getMessageStateCompletedEventHandler getMessageStateCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://webservice.smsrelay.armaghan.net/", ResponseNamespace = "http://webservice.smsrelay.armaghan.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userResult getUserInfo([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string password)
        {
            object[] results = this.Invoke("getUserInfo", new object[] {
                    username,
                    password});
            return ((userResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetUserInfo(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getUserInfo", new object[] {
                    username,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public userResult EndgetUserInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((userResult)(results[0]));
        }

        /// <remarks/>
        public void getUserInfoAsync(string username, string password)
        {
            this.getUserInfoAsync(username, password, null);
        }

        /// <remarks/>
        public void getUserInfoAsync(string username, string password, object userState)
        {
            if ((this.getUserInfoOperationCompleted == null))
            {
                this.getUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserInfoOperationCompleted);
            }
            this.InvokeAsync("getUserInfo", new object[] {
                    username,
                    password}, this.getUserInfoOperationCompleted, userState);
        }

        private void OngetUserInfoOperationCompleted(object arg)
        {
            if ((this.getUserInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserInfoCompleted(this, new getUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://webservice.smsrelay.armaghan.net/", ResponseNamespace = "http://webservice.smsrelay.armaghan.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public countResult getReceivedMessageCount([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string password)
        {
            object[] results = this.Invoke("getReceivedMessageCount", new object[] {
                    username,
                    password});
            return ((countResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetReceivedMessageCount(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getReceivedMessageCount", new object[] {
                    username,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public countResult EndgetReceivedMessageCount(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((countResult)(results[0]));
        }

        /// <remarks/>
        public void getReceivedMessageCountAsync(string username, string password)
        {
            this.getReceivedMessageCountAsync(username, password, null);
        }

        /// <remarks/>
        public void getReceivedMessageCountAsync(string username, string password, object userState)
        {
            if ((this.getReceivedMessageCountOperationCompleted == null))
            {
                this.getReceivedMessageCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReceivedMessageCountOperationCompleted);
            }
            this.InvokeAsync("getReceivedMessageCount", new object[] {
                    username,
                    password}, this.getReceivedMessageCountOperationCompleted, userState);
        }

        private void OngetReceivedMessageCountOperationCompleted(object arg)
        {
            if ((this.getReceivedMessageCountCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReceivedMessageCountCompleted(this, new getReceivedMessageCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://webservice.smsrelay.armaghan.net/", ResponseNamespace = "http://webservice.smsrelay.armaghan.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public messageResult pullReceivedMessages([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string password)
        {
            object[] results = this.Invoke("pullReceivedMessages", new object[] {
                    username,
                    password});
            return ((messageResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginpullReceivedMessages(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("pullReceivedMessages", new object[] {
                    username,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public messageResult EndpullReceivedMessages(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((messageResult)(results[0]));
        }

        /// <remarks/>
        public void pullReceivedMessagesAsync(string username, string password)
        {
            this.pullReceivedMessagesAsync(username, password, null);
        }

        /// <remarks/>
        public void pullReceivedMessagesAsync(string username, string password, object userState)
        {
            if ((this.pullReceivedMessagesOperationCompleted == null))
            {
                this.pullReceivedMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpullReceivedMessagesOperationCompleted);
            }
            this.InvokeAsync("pullReceivedMessages", new object[] {
                    username,
                    password}, this.pullReceivedMessagesOperationCompleted, userState);
        }

        private void OnpullReceivedMessagesOperationCompleted(object arg)
        {
            if ((this.pullReceivedMessagesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pullReceivedMessagesCompleted(this, new pullReceivedMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://webservice.smsrelay.armaghan.net/", ResponseNamespace = "http://webservice.smsrelay.armaghan.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public referenceResult sendMessageManyToMany([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute("originator", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] originator, [System.Xml.Serialization.XmlElementAttribute("destination", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] destination, [System.Xml.Serialization.XmlElementAttribute("content", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] content)
        {
            object[] results = this.Invoke("sendMessageManyToMany", new object[] {
                    username,
                    password,
                    originator,
                    destination,
                    content});
            return ((referenceResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginsendMessageManyToMany(string username, string password, string[] originator, string[] destination, string[] content, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("sendMessageManyToMany", new object[] {
                    username,
                    password,
                    originator,
                    destination,
                    content}, callback, asyncState);
        }

        /// <remarks/>
        public referenceResult EndsendMessageManyToMany(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((referenceResult)(results[0]));
        }

        /// <remarks/>
        public void sendMessageManyToManyAsync(string username, string password, string[] originator, string[] destination, string[] content)
        {
            this.sendMessageManyToManyAsync(username, password, originator, destination, content, null);
        }

        /// <remarks/>
        public void sendMessageManyToManyAsync(string username, string password, string[] originator, string[] destination, string[] content, object userState)
        {
            if ((this.sendMessageManyToManyOperationCompleted == null))
            {
                this.sendMessageManyToManyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMessageManyToManyOperationCompleted);
            }
            this.InvokeAsync("sendMessageManyToMany", new object[] {
                    username,
                    password,
                    originator,
                    destination,
                    content}, this.sendMessageManyToManyOperationCompleted, userState);
        }

        private void OnsendMessageManyToManyOperationCompleted(object arg)
        {
            if ((this.sendMessageManyToManyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendMessageManyToManyCompleted(this, new sendMessageManyToManyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://webservice.smsrelay.armaghan.net/", ResponseNamespace = "http://webservice.smsrelay.armaghan.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public referenceResult sendMessageOneToMany([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string originator, [System.Xml.Serialization.XmlElementAttribute("destination", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] destination, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string content)
        {
            object[] results = this.Invoke("sendMessageOneToMany", new object[] {
                    username,
                    password,
                    originator,
                    destination,
                    content});
            return ((referenceResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginsendMessageOneToMany(string username, string password, string originator, string[] destination, string content, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("sendMessageOneToMany", new object[] {
                    username,
                    password,
                    originator,
                    destination,
                    content}, callback, asyncState);
        }

        /// <remarks/>
        public referenceResult EndsendMessageOneToMany(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((referenceResult)(results[0]));
        }

        /// <remarks/>
        public void sendMessageOneToManyAsync(string username, string password, string originator, string[] destination, string content)
        {
            this.sendMessageOneToManyAsync(username, password, originator, destination, content, null);
        }

        /// <remarks/>
        public void sendMessageOneToManyAsync(string username, string password, string originator, string[] destination, string content, object userState)
        {
            if ((this.sendMessageOneToManyOperationCompleted == null))
            {
                this.sendMessageOneToManyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMessageOneToManyOperationCompleted);
            }
            this.InvokeAsync("sendMessageOneToMany", new object[] {
                    username,
                    password,
                    originator,
                    destination,
                    content}, this.sendMessageOneToManyOperationCompleted, userState);
        }

        private void OnsendMessageOneToManyOperationCompleted(object arg)
        {
            if ((this.sendMessageOneToManyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendMessageOneToManyCompleted(this, new sendMessageOneToManyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://webservice.smsrelay.armaghan.net/", ResponseNamespace = "http://webservice.smsrelay.armaghan.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public messageStateResult getMessageState([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string username, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute("id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] long[] id)
        {
            object[] results = this.Invoke("getMessageState", new object[] {
                    username,
                    password,
                    id});
            return ((messageStateResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetMessageState(string username, string password, long[] id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getMessageState", new object[] {
                    username,
                    password,
                    id}, callback, asyncState);
        }

        /// <remarks/>
        public messageStateResult EndgetMessageState(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((messageStateResult)(results[0]));
        }

        /// <remarks/>
        public void getMessageStateAsync(string username, string password, long[] id)
        {
            this.getMessageStateAsync(username, password, id, null);
        }

        /// <remarks/>
        public void getMessageStateAsync(string username, string password, long[] id, object userState)
        {
            if ((this.getMessageStateOperationCompleted == null))
            {
                this.getMessageStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageStateOperationCompleted);
            }
            this.InvokeAsync("getMessageState", new object[] {
                    username,
                    password,
                    id}, this.getMessageStateOperationCompleted, userState);
        }

        private void OngetMessageStateOperationCompleted(object arg)
        {
            if ((this.getMessageStateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageStateCompleted(this, new getMessageStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class userResult
    {

        private user userField;

        private error errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public user user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class user
    {

        private string usernameField;

        private double creditField;

        private string deliveryUrlField;

        private string receiveUrlField;

        private System.DateTime expirationDateField;

        private string[] iPsField;

        private string[] numbersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string deliveryUrl
        {
            get
            {
                return this.deliveryUrlField;
            }
            set
            {
                this.deliveryUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string receiveUrl
        {
            get
            {
                return this.receiveUrlField;
            }
            set
            {
                this.receiveUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime expirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IPs", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] IPs
        {
            get
            {
                return this.iPsField;
            }
            set
            {
                this.iPsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numbers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] numbers
        {
            get
            {
                return this.numbersField;
            }
            set
            {
                this.numbersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class messageState
    {

        private long idField;

        private int stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class messageStateResult
    {

        private messageState[] statesField;

        private error errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("states", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public messageState[] states
        {
            get
            {
                return this.statesField;
            }
            set
            {
                this.statesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class error
    {

        private int errorCodeField;

        private System.DateTime timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class referenceResult
    {

        private System.Nullable<long>[] referencesField;

        private error errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("references", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public System.Nullable<long>[] references
        {
            get
            {
                return this.referencesField;
            }
            set
            {
                this.referencesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class message
    {

        private string originatorField;

        private string destinationField;

        private string contentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string originator
        {
            get
            {
                return this.originatorField;
            }
            set
            {
                this.originatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class messageResult
    {

        private message[] messagesField;

        private error errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public message[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.smsrelay.armaghan.net/")]
    public partial class countResult
    {

        private int countField;

        private error errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getUserInfoCompletedEventHandler(object sender, getUserInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public userResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((userResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getReceivedMessageCountCompletedEventHandler(object sender, getReceivedMessageCountCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReceivedMessageCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getReceivedMessageCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public countResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((countResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void pullReceivedMessagesCompletedEventHandler(object sender, pullReceivedMessagesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pullReceivedMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal pullReceivedMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public messageResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((messageResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void sendMessageManyToManyCompletedEventHandler(object sender, sendMessageManyToManyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendMessageManyToManyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal sendMessageManyToManyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public referenceResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((referenceResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void sendMessageOneToManyCompletedEventHandler(object sender, sendMessageOneToManyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendMessageOneToManyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal sendMessageOneToManyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public referenceResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((referenceResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getMessageStateCompletedEventHandler(object sender, getMessageStateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getMessageStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public messageStateResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((messageStateResult)(this.results[0]));
            }
        }
    }
}