--گزارش بر روی سرور نهایی شد پس باید روی لوکال هم به روز رسانی میشد
--13930928 19:31
--UPDATE RL
--SET Template = RR.Template,
--	[TimeStamp] = RR.[TimeStamp]
--FROM
--	ReportTemplate RL
--INNER JOIN 
--	[78.39.252.109].CRM.dbo.ReportTemplate RR ON RL.ID = RR.ID
--WHERE 
--	Rl.ID = 254 AND RR.ID = 254

