//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace CRM.Application.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPhoneStatusService", Namespace="http://tempuri.org/")]
    public partial class PhoneStatusService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsDebtorOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsDebtorByRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDebtStatusListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDebtStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhoneStatusService() {
            this.Url = "http://217.218.241.74:5000/Service.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsDebtorCompletedEventHandler IsDebtorCompleted;
        
        /// <remarks/>
        public event IsDebtorByRangeCompletedEventHandler IsDebtorByRangeCompleted;
        
        /// <remarks/>
        public event GetDebtStatusListCompletedEventHandler GetDebtStatusListCompleted;
        
        /// <remarks/>
        public event GetDebtStatusCompletedEventHandler GetDebtStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhoneStatusService/IsDebtor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsDebtor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, long debt, [System.Xml.Serialization.XmlIgnoreAttribute()] bool debtSpecified, out long IsDebtorResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsDebtorResultSpecified) {
            object[] results = this.Invoke("IsDebtor", new object[] {
                        phoneNumber,
                        debt,
                        debtSpecified});
            IsDebtorResult = ((long)(results[0]));
            IsDebtorResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IsDebtorAsync(string phoneNumber, long debt, bool debtSpecified) {
            this.IsDebtorAsync(phoneNumber, debt, debtSpecified, null);
        }
        
        /// <remarks/>
        public void IsDebtorAsync(string phoneNumber, long debt, bool debtSpecified, object userState) {
            if ((this.IsDebtorOperationCompleted == null)) {
                this.IsDebtorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsDebtorOperationCompleted);
            }
            this.InvokeAsync("IsDebtor", new object[] {
                        phoneNumber,
                        debt,
                        debtSpecified}, this.IsDebtorOperationCompleted, userState);
        }
        
        private void OnIsDebtorOperationCompleted(object arg) {
            if ((this.IsDebtorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsDebtorCompleted(this, new IsDebtorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhoneStatusService/IsDebtorByRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] IsDebtorByRange(long debt, [System.Xml.Serialization.XmlIgnoreAttribute()] bool debtSpecified) {
            object[] results = this.Invoke("IsDebtorByRange", new object[] {
                        debt,
                        debtSpecified});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void IsDebtorByRangeAsync(long debt, bool debtSpecified) {
            this.IsDebtorByRangeAsync(debt, debtSpecified, null);
        }
        
        /// <remarks/>
        public void IsDebtorByRangeAsync(long debt, bool debtSpecified, object userState) {
            if ((this.IsDebtorByRangeOperationCompleted == null)) {
                this.IsDebtorByRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsDebtorByRangeOperationCompleted);
            }
            this.InvokeAsync("IsDebtorByRange", new object[] {
                        debt,
                        debtSpecified}, this.IsDebtorByRangeOperationCompleted, userState);
        }
        
        private void OnIsDebtorByRangeOperationCompleted(object arg) {
            if ((this.IsDebtorByRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsDebtorByRangeCompleted(this, new IsDebtorByRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhoneStatusService/GetDebtStatusList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Abonman.Data")]
        public DebtorStat[] GetDebtStatusList([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] phoneNumbers) {
            object[] results = this.Invoke("GetDebtStatusList", new object[] {
                        phoneNumbers});
            return ((DebtorStat[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDebtStatusListAsync(string[] phoneNumbers) {
            this.GetDebtStatusListAsync(phoneNumbers, null);
        }
        
        /// <remarks/>
        public void GetDebtStatusListAsync(string[] phoneNumbers, object userState) {
            if ((this.GetDebtStatusListOperationCompleted == null)) {
                this.GetDebtStatusListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDebtStatusListOperationCompleted);
            }
            this.InvokeAsync("GetDebtStatusList", new object[] {
                        phoneNumbers}, this.GetDebtStatusListOperationCompleted, userState);
        }
        
        private void OnGetDebtStatusListOperationCompleted(object arg) {
            if ((this.GetDebtStatusListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDebtStatusListCompleted(this, new GetDebtStatusListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPhoneStatusService/GetDebtStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDebtStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, out long GetDebtStatusResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetDebtStatusResultSpecified) {
            object[] results = this.Invoke("GetDebtStatus", new object[] {
                        phoneNumber});
            GetDebtStatusResult = ((long)(results[0]));
            GetDebtStatusResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GetDebtStatusAsync(string phoneNumber) {
            this.GetDebtStatusAsync(phoneNumber, null);
        }
        
        /// <remarks/>
        public void GetDebtStatusAsync(string phoneNumber, object userState) {
            if ((this.GetDebtStatusOperationCompleted == null)) {
                this.GetDebtStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDebtStatusOperationCompleted);
            }
            this.InvokeAsync("GetDebtStatus", new object[] {
                        phoneNumber}, this.GetDebtStatusOperationCompleted, userState);
        }
        
        private void OnGetDebtStatusOperationCompleted(object arg) {
            if ((this.GetDebtStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDebtStatusCompleted(this, new GetDebtStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Abonman.Data")]
    public partial class DebtorStat {
        
        private long debtField;
        
        private bool debtFieldSpecified;
        
        private string phoneNoField;
        
        /// <remarks/>
        public long Debt {
            get {
                return this.debtField;
            }
            set {
                this.debtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebtSpecified {
            get {
                return this.debtFieldSpecified;
            }
            set {
                this.debtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void IsDebtorCompletedEventHandler(object sender, IsDebtorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsDebtorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsDebtorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long IsDebtorResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IsDebtorResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void IsDebtorByRangeCompletedEventHandler(object sender, IsDebtorByRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsDebtorByRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsDebtorByRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDebtStatusListCompletedEventHandler(object sender, GetDebtStatusListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDebtStatusListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDebtStatusListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DebtorStat[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DebtorStat[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDebtStatusCompletedEventHandler(object sender, GetDebtStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDebtStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDebtStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long GetDebtStatusResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GetDebtStatusResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591