//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace CRM.Data.ElkaWebSevice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="web_service_TransmissionSoap", Namespace="http://localhost/Web_Service_Tranamission")]
    public partial class web_service_Transmission : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dataBasIsActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback handshakeOperationCompleted;
        
        private System.Threading.SendOrPostCallback transfer_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback transfer_Data1OperationCompleted;
        
        private System.Threading.SendOrPostCallback Sync_Base_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sync_Base_Data1OperationCompleted;
        
        private System.Threading.SendOrPostCallback Sync_KafuSwap_InfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sync_KafuSwap_Info1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public web_service_Transmission() {
            this.Url = global::CRM.Data.Properties.Settings.Default.CRM_Data_ElkaWebSevice_web_service_Transmission;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dataBasIsActiveCompletedEventHandler dataBasIsActiveCompleted;
        
        /// <remarks/>
        public event handshakeCompletedEventHandler handshakeCompleted;
        
        /// <remarks/>
        public event transfer_DataCompletedEventHandler transfer_DataCompleted;
        
        /// <remarks/>
        public event transfer_Data1CompletedEventHandler transfer_Data1Completed;
        
        /// <remarks/>
        public event Sync_Base_DataCompletedEventHandler Sync_Base_DataCompleted;
        
        /// <remarks/>
        public event Sync_Base_Data1CompletedEventHandler Sync_Base_Data1Completed;
        
        /// <remarks/>
        public event Sync_KafuSwap_InfoCompletedEventHandler Sync_KafuSwap_InfoCompleted;
        
        /// <remarks/>
        public event Sync_KafuSwap_Info1CompletedEventHandler Sync_KafuSwap_Info1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/dataBasIsActive", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int dataBasIsActive(string Code, int Os_Code) {
            object[] results = this.Invoke("dataBasIsActive", new object[] {
                        Code,
                        Os_Code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void dataBasIsActiveAsync(string Code, int Os_Code) {
            this.dataBasIsActiveAsync(Code, Os_Code, null);
        }
        
        /// <remarks/>
        public void dataBasIsActiveAsync(string Code, int Os_Code, object userState) {
            if ((this.dataBasIsActiveOperationCompleted == null)) {
                this.dataBasIsActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataBasIsActiveOperationCompleted);
            }
            this.InvokeAsync("dataBasIsActive", new object[] {
                        Code,
                        Os_Code}, this.dataBasIsActiveOperationCompleted, userState);
        }
        
        private void OndataBasIsActiveOperationCompleted(object arg) {
            if ((this.dataBasIsActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataBasIsActiveCompleted(this, new dataBasIsActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/handshake", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int handshake(ref int Priority, ref string S_Time, string Code, ref string E_Time, int Os_Code) {
            object[] results = this.Invoke("handshake", new object[] {
                        Priority,
                        S_Time,
                        Code,
                        E_Time,
                        Os_Code});
            Priority = ((int)(results[1]));
            S_Time = ((string)(results[2]));
            E_Time = ((string)(results[3]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void handshakeAsync(int Priority, string S_Time, string Code, string E_Time, int Os_Code) {
            this.handshakeAsync(Priority, S_Time, Code, E_Time, Os_Code, null);
        }
        
        /// <remarks/>
        public void handshakeAsync(int Priority, string S_Time, string Code, string E_Time, int Os_Code, object userState) {
            if ((this.handshakeOperationCompleted == null)) {
                this.handshakeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhandshakeOperationCompleted);
            }
            this.InvokeAsync("handshake", new object[] {
                        Priority,
                        S_Time,
                        Code,
                        E_Time,
                        Os_Code}, this.handshakeOperationCompleted, userState);
        }
        
        private void OnhandshakeOperationCompleted(object arg) {
            if ((this.handshakeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.handshakeCompleted(this, new handshakeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/transfer_Data", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int transfer_Data(System.Data.DataSet Ds, string code, ref string C_F_ID) {
            object[] results = this.Invoke("transfer_Data", new object[] {
                        Ds,
                        code,
                        C_F_ID});
            C_F_ID = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void transfer_DataAsync(System.Data.DataSet Ds, string code, string C_F_ID) {
            this.transfer_DataAsync(Ds, code, C_F_ID, null);
        }
        
        /// <remarks/>
        public void transfer_DataAsync(System.Data.DataSet Ds, string code, string C_F_ID, object userState) {
            if ((this.transfer_DataOperationCompleted == null)) {
                this.transfer_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontransfer_DataOperationCompleted);
            }
            this.InvokeAsync("transfer_Data", new object[] {
                        Ds,
                        code,
                        C_F_ID}, this.transfer_DataOperationCompleted, userState);
        }
        
        private void Ontransfer_DataOperationCompleted(object arg) {
            if ((this.transfer_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transfer_DataCompleted(this, new transfer_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="transfer_Data1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/transfer_Data_Json", RequestElementName="transfer_Data_Json", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseElementName="transfer_Data_JsonResponse", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("transfer_Data_JsonResult")]
        public int transfer_Data(string JsonString, string code, ref string C_F_ID) {
            object[] results = this.Invoke("transfer_Data1", new object[] {
                        JsonString,
                        code,
                        C_F_ID});
            C_F_ID = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void transfer_Data1Async(string JsonString, string code, string C_F_ID) {
            this.transfer_Data1Async(JsonString, code, C_F_ID, null);
        }
        
        /// <remarks/>
        public void transfer_Data1Async(string JsonString, string code, string C_F_ID, object userState) {
            if ((this.transfer_Data1OperationCompleted == null)) {
                this.transfer_Data1OperationCompleted = new System.Threading.SendOrPostCallback(this.Ontransfer_Data1OperationCompleted);
            }
            this.InvokeAsync("transfer_Data1", new object[] {
                        JsonString,
                        code,
                        C_F_ID}, this.transfer_Data1OperationCompleted, userState);
        }
        
        private void Ontransfer_Data1OperationCompleted(object arg) {
            if ((this.transfer_Data1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transfer_Data1Completed(this, new transfer_Data1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/Sync_Base_Data", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Sync_Base_Data(System.Data.DataSet Ds, string code) {
            object[] results = this.Invoke("Sync_Base_Data", new object[] {
                        Ds,
                        code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Sync_Base_DataAsync(System.Data.DataSet Ds, string code) {
            this.Sync_Base_DataAsync(Ds, code, null);
        }
        
        /// <remarks/>
        public void Sync_Base_DataAsync(System.Data.DataSet Ds, string code, object userState) {
            if ((this.Sync_Base_DataOperationCompleted == null)) {
                this.Sync_Base_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSync_Base_DataOperationCompleted);
            }
            this.InvokeAsync("Sync_Base_Data", new object[] {
                        Ds,
                        code}, this.Sync_Base_DataOperationCompleted, userState);
        }
        
        private void OnSync_Base_DataOperationCompleted(object arg) {
            if ((this.Sync_Base_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sync_Base_DataCompleted(this, new Sync_Base_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="Sync_Base_Data1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/Sync_Base_Data_JSON", RequestElementName="Sync_Base_Data_JSON", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseElementName="Sync_Base_Data_JSONResponse", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sync_Base_Data_JSONResult")]
        public int Sync_Base_Data(string JsonString, string code) {
            object[] results = this.Invoke("Sync_Base_Data1", new object[] {
                        JsonString,
                        code});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Sync_Base_Data1Async(string JsonString, string code) {
            this.Sync_Base_Data1Async(JsonString, code, null);
        }
        
        /// <remarks/>
        public void Sync_Base_Data1Async(string JsonString, string code, object userState) {
            if ((this.Sync_Base_Data1OperationCompleted == null)) {
                this.Sync_Base_Data1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSync_Base_Data1OperationCompleted);
            }
            this.InvokeAsync("Sync_Base_Data1", new object[] {
                        JsonString,
                        code}, this.Sync_Base_Data1OperationCompleted, userState);
        }
        
        private void OnSync_Base_Data1OperationCompleted(object arg) {
            if ((this.Sync_Base_Data1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sync_Base_Data1Completed(this, new Sync_Base_Data1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/Sync_KafuSwap_Info", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Sync_KafuSwap_Info(int osCode, string code, System.Data.DataSet Ds, ref string insertedIDs) {
            object[] results = this.Invoke("Sync_KafuSwap_Info", new object[] {
                        osCode,
                        code,
                        Ds,
                        insertedIDs});
            insertedIDs = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Sync_KafuSwap_InfoAsync(int osCode, string code, System.Data.DataSet Ds, string insertedIDs) {
            this.Sync_KafuSwap_InfoAsync(osCode, code, Ds, insertedIDs, null);
        }
        
        /// <remarks/>
        public void Sync_KafuSwap_InfoAsync(int osCode, string code, System.Data.DataSet Ds, string insertedIDs, object userState) {
            if ((this.Sync_KafuSwap_InfoOperationCompleted == null)) {
                this.Sync_KafuSwap_InfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSync_KafuSwap_InfoOperationCompleted);
            }
            this.InvokeAsync("Sync_KafuSwap_Info", new object[] {
                        osCode,
                        code,
                        Ds,
                        insertedIDs}, this.Sync_KafuSwap_InfoOperationCompleted, userState);
        }
        
        private void OnSync_KafuSwap_InfoOperationCompleted(object arg) {
            if ((this.Sync_KafuSwap_InfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sync_KafuSwap_InfoCompleted(this, new Sync_KafuSwap_InfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="Sync_KafuSwap_Info1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Web_Service_Tranamission/Sync_KafuSwap_Info_Json", RequestElementName="Sync_KafuSwap_Info_Json", RequestNamespace="http://localhost/Web_Service_Tranamission", ResponseElementName="Sync_KafuSwap_Info_JsonResponse", ResponseNamespace="http://localhost/Web_Service_Tranamission", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sync_KafuSwap_Info_JsonResult")]
        public int Sync_KafuSwap_Info(int osCode, string code, string JsonString, ref string insertedIDs) {
            object[] results = this.Invoke("Sync_KafuSwap_Info1", new object[] {
                        osCode,
                        code,
                        JsonString,
                        insertedIDs});
            insertedIDs = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Sync_KafuSwap_Info1Async(int osCode, string code, string JsonString, string insertedIDs) {
            this.Sync_KafuSwap_Info1Async(osCode, code, JsonString, insertedIDs, null);
        }
        
        /// <remarks/>
        public void Sync_KafuSwap_Info1Async(int osCode, string code, string JsonString, string insertedIDs, object userState) {
            if ((this.Sync_KafuSwap_Info1OperationCompleted == null)) {
                this.Sync_KafuSwap_Info1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSync_KafuSwap_Info1OperationCompleted);
            }
            this.InvokeAsync("Sync_KafuSwap_Info1", new object[] {
                        osCode,
                        code,
                        JsonString,
                        insertedIDs}, this.Sync_KafuSwap_Info1OperationCompleted, userState);
        }
        
        private void OnSync_KafuSwap_Info1OperationCompleted(object arg) {
            if ((this.Sync_KafuSwap_Info1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sync_KafuSwap_Info1Completed(this, new Sync_KafuSwap_Info1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void dataBasIsActiveCompletedEventHandler(object sender, dataBasIsActiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataBasIsActiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataBasIsActiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void handshakeCompletedEventHandler(object sender, handshakeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class handshakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal handshakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string S_Time {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string E_Time {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void transfer_DataCompletedEventHandler(object sender, transfer_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transfer_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transfer_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string C_F_ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void transfer_Data1CompletedEventHandler(object sender, transfer_Data1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transfer_Data1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transfer_Data1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string C_F_ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Sync_Base_DataCompletedEventHandler(object sender, Sync_Base_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sync_Base_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sync_Base_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Sync_Base_Data1CompletedEventHandler(object sender, Sync_Base_Data1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sync_Base_Data1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sync_Base_Data1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Sync_KafuSwap_InfoCompletedEventHandler(object sender, Sync_KafuSwap_InfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sync_KafuSwap_InfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sync_KafuSwap_InfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string insertedIDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Sync_KafuSwap_Info1CompletedEventHandler(object sender, Sync_KafuSwap_Info1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sync_KafuSwap_Info1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sync_KafuSwap_Info1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string insertedIDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591