SELECT * , [TEL_NUMBER] , [CI_CODE] , [CEN_NAME]
FROM
(SELECT BE.[ETS_ID] AS BASE_ETESALI_ETS_ID
  FROM [ORACLECRM]..[SCOTT].[BASE_ETESALI] AS BE  JOIN [ORACLECRM]..[SCOTT].[ETESALI] AS E ON E.[ETS_ID] = BE.[ETS_ID]
  GROUP BY BE.[ETS_ID] , PCM_STATUS
  HAVING  PCM_STATUS = 0 AND COUNT( BE.[ETS_ID]) > 1) AS T 
  JOIN [ORACLECRM]..[SCOTT].[ETESALI] AS E ON E.ETS_ID= BASE_ETESALI_ETS_ID 
  LEFT JOIN [ORACLECRM]..[SCOTT].[TELEPHONEINFORMATION] AS Te ON E.FI_CODE = Te.FI_CODE
  LEFT  JOIN [ORACLECRM]..[SCOTT].[CENTER] AS CEN ON CEN.[CEN_CODE] = Te.[CENTER_CODE] 
  ORDER BY BASE_ETESALI_ETS_ID
GO 